security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: bcrypt
    providers:
        # Replace "your_user_provider" with the name of your user provider
        your_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: your_user_provider # Update with your User Provider name
            custom_authenticator: App\Security\AppCustomAuthenticator
            logout:
                path: app_logout

    access_control:
        # ...
