--------------------------------------------------------
--  Fichier cr�� - mercredi-mars-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMINISTRATION
--------------------------------------------------------

  CREATE TABLE "ANAS"."ADMINISTRATION" 
   (	"ID" NUMBER(20,0) DEFAULT 1, 
	"FONCTION" VARCHAR2(20 BYTE), 
	"ADRESSE" NUMBER, 
	"NUMTEL" NUMBER(8,0), 
	"D�PARTEMENT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AMBULANCE
--------------------------------------------------------

  CREATE TABLE "ANAS"."AMBULANCE" 
   (	"MATRICULE" VARCHAR2(20 BYTE), 
	"MOD�LE" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"NOMCHAUFFEUR" VARCHAR2(20 BYTE), 
	"NUMTEL" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENT
--------------------------------------------------------

  CREATE TABLE "ANAS"."EQUIPEMENT" 
   (	"ID" NUMBER DEFAULT 1, 
	"NOM" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"DAT" DATE, 
	"THEME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HOPITAL
--------------------------------------------------------

  CREATE TABLE "ANAS"."HOPITAL" 
   (	"NOM" VARCHAR2(20 BYTE) DEFAULT 1, 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"NUMTEL" NUMBER(8,0), 
	"TYPE" VARCHAR2(20 BYTE), 
	"SITEWEB" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table M�DECIN
--------------------------------------------------------

  CREATE TABLE "ANAS"."M�DECIN" 
   (	"CIN" NUMBER DEFAULT 1, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"SP�CIALIT�" VARCHAR2(20 BYTE), 
	"NUMTEL" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PATIENT
--------------------------------------------------------

  CREATE TABLE "ANAS"."PATIENT" 
   (	"CIN" NUMBER DEFAULT 1, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DTN" DATE, 
	"SEXE" VARCHAR2(20 BYTE), 
	"NUMTEL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ANAS.ADMINISTRATION
SET DEFINE OFF;
REM INSERTING into ANAS.AMBULANCE
SET DEFINE OFF;
REM INSERTING into ANAS.EQUIPEMENT
SET DEFINE OFF;
REM INSERTING into ANAS.HOPITAL
SET DEFINE OFF;
REM INSERTING into ANAS."M�DECIN"
SET DEFINE OFF;
REM INSERTING into ANAS.PATIENT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ADMINISTRATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANAS"."ADMINISTRATION_PK" ON "ANAS"."ADMINISTRATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index M�DECIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANAS"."M�DECIN_PK" ON "ANAS"."M�DECIN" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PATIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANAS"."PATIENT_PK" ON "ANAS"."PATIENT" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index HOPITAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANAS"."HOPITAL_PK" ON "ANAS"."HOPITAL" ("NOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EQUIPEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANAS"."EQUIPEMENT_PK" ON "ANAS"."EQUIPEMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AMBULANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANAS"."AMBULANCE_PK" ON "ANAS"."AMBULANCE" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table M�DECIN
--------------------------------------------------------

  ALTER TABLE "ANAS"."M�DECIN" ADD CONSTRAINT "M�DECIN_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANAS"."M�DECIN" MODIFY ("NUMTEL" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."M�DECIN" MODIFY ("SP�CIALIT�" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."M�DECIN" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."M�DECIN" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."M�DECIN" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPEMENT
--------------------------------------------------------

  ALTER TABLE "ANAS"."EQUIPEMENT" ADD CONSTRAINT "EQUIPEMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANAS"."EQUIPEMENT" MODIFY ("THEME" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."EQUIPEMENT" MODIFY ("DAT" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."EQUIPEMENT" MODIFY ("ETAT" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."EQUIPEMENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."EQUIPEMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMINISTRATION
--------------------------------------------------------

  ALTER TABLE "ANAS"."ADMINISTRATION" ADD CONSTRAINT "ADMINISTRATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANAS"."ADMINISTRATION" MODIFY ("D�PARTEMENT" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."ADMINISTRATION" MODIFY ("NUMTEL" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."ADMINISTRATION" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."ADMINISTRATION" MODIFY ("FONCTION" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."ADMINISTRATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AMBULANCE
--------------------------------------------------------

  ALTER TABLE "ANAS"."AMBULANCE" ADD CONSTRAINT "AMBULANCE_PK" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANAS"."AMBULANCE" MODIFY ("NUMTEL" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."AMBULANCE" MODIFY ("NOMCHAUFFEUR" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."AMBULANCE" MODIFY ("ETAT" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."AMBULANCE" MODIFY ("MOD�LE" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."AMBULANCE" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PATIENT
--------------------------------------------------------

  ALTER TABLE "ANAS"."PATIENT" ADD CONSTRAINT "PATIENT_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANAS"."PATIENT" MODIFY ("NUMTEL" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."PATIENT" MODIFY ("SEXE" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."PATIENT" MODIFY ("DTN" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."PATIENT" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."PATIENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."PATIENT" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HOPITAL
--------------------------------------------------------

  ALTER TABLE "ANAS"."HOPITAL" ADD CONSTRAINT "HOPITAL_PK" PRIMARY KEY ("NOM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANAS"."HOPITAL" MODIFY ("SITEWEB" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."HOPITAL" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."HOPITAL" MODIFY ("NUMTEL" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."HOPITAL" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."HOPITAL" MODIFY ("NOM" NOT NULL ENABLE);
