# config/packages/swiftmailer.yaml

swiftmailer:
    transport: smtp
    host: smtp.gmail.com
    port: 587
    encryption: tls
    username: ines.bouraoui@esprit.tn
    password: IngridBergman
    spool: { type: memory }
